repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-  repo: https://github.com/nicklockwood/SwiftFormat
   rev: 0.53.1
   hooks:
   - id: swiftformat
     args: [--config, .swiftformat]
-  repo: https://github.com/realm/SwiftLint
   rev: 0.54.0
   hooks:
   - id: swiftlint
     args: [--config, .swiftlint.yml]
-  repo: https://github.com/RandomActsOfCode/dowyi
   rev: 0.1.0
   hooks:
   - id: dowyi
