name: build-macos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code_checks:
    name: Code Checks
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2.3.0
        with:
          swift-version: "6"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Precommit
        run: pip install pre-commit
      - name: Code Checks
        uses: pre-commit/action@v3.0.1
      - name: Build
        run: swift build
      - name: Test
        run: swift test
